# Generated by Django 6.0.4 on 2026-04-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Technology & Coding'), ('academic', 'Academic Tutoring'), ('language', 'Language & Writing'), ('music', 'Music & Arts'), ('design', 'Design & Media'), ('fitness', 'Fitness & Wellness'), ('cooking', 'Cooking & Food'), ('other', 'Other')], default='other', max_length=50)),
                ('rate', models.CharField(help_text='e.g. Free, $15/hr, Trade for coffee', max_length=100)),
                ('contact', models.CharField(help_text='How students should reach you', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
